export const CP_DASHBOARD_FULL = 'CP_DASHBOARD_FULL';
export const CP_INWARD_FULL = 'CP_INWARD_FULL';
export const CP_ORDER_FULL = 'CP_ORDER_FULL';
export const CP_WAREHOUSE_FULL = 'CP_WAREHOUSE_FULL';
export const CP_PRODUCT_FULL = 'CP_PRODUCT_FULL';
export const CP_LOGISTIC_FULL = 'CP_LOGISTIC_FULL';